pipeline:
  check_params:
    image: mongo:3.2.9
    commands:
        - cat lab3a/lab3a.js
        - sleep 15 
 
  grade_lab3a:
    image: mongo:3.2.9
    commands:
        - mongo --host mongodb < lab3a/lab3a.js 

services:
  mongodb:
    image: mongo:3.2.9
    command: [ --smallfiles ]
