pipeline:
  check_params:
    image: uiscsc561/neo4j
    commands:
        - cat lab5a/lab5a.cypher
        - sleep 5 
        
  grade_lab5a:
    image: uiscsc561/neo4j
    commands:
        - cat lab5a/lab5a.cypher | /var/lib/neo4j/bin/cypher-shell -a neo4j --format plain --fail-at-end --debug --non-interactive
        - /var/lib/neo4j/bin/cypher-shell -a neo4j --format verbose "MATCH (n)-[r]->(m) RETURN n,r,m;"

services:
  neo4j:
    image: uiscsc561/neo4j
