pipeline:
  check_params:
    image: uiscsc561/riak
    commands:
        - sleep 30 
        - curl -s http://riak:8098/ping
        - cat lab2b/lab2b.sh
 
  grade_lab2b:
    image: uiscsc561/riak
    commands:
        - bash lab2b/lab2b.sh 

services:
  riak:
    image: uiscsc561/riak
    ports:
      - "8098:8098" 
