pipeline:
  check_params:
    image: dasudian/riak
    commands:
        - sleep 30 
        - curl http://riak:8098/ping
        - md5sum lab2a/lab2a.sh
        - cat lab2a/lab2a.sh
 
  grade_lab2a:
    image: dasudian/riak
    commands:
        - bash lab2a/lab2a.sh 

services:
  riak:
    image: dasudian/riak
    ports:
      - "8098:8098" 
