pipeline:
  check_params:
    image: uiscsc561/hbase-slave
    environment:
       - JAVA_HOME=/usr/lib/jvm/default-jvm
    commands:
        - cat lab4a/lab4a.rb
        - cp /etc/hosts /tmp/hosts
        - sed -i 's/localhost/localdomain/g' /tmp/hosts
        - echo "172.20.0.2     hbase-docker localhost" >> /tmp/hosts 
        - echo "$(cat /tmp/hosts)" > /etc/hosts 
        - echo "version"  | hbase shell
        - sleep 10 
 
  grade_lab4a:
    image: uiscsc561/hbase-slave
    environment:
       - JAVA_HOME=/usr/lib/jvm/default-jvm
    commands:
        - cp /etc/hosts /tmp/hosts
        - sed -i 's/localhost/localdomain/g' /tmp/hosts
        - scp drone@csc570e.uis.edu:/home/drone/hostname /tmp/
        - cat /tmp/hostname >> /tmp/hosts
        - echo "$(cat /tmp/hosts)" > /etc/hosts 
        - hbase shell -n lab4a/base.txt
        - hbase shell -n lab4a/lab4a.rb

services:
  hbase-docker:
    image: uiscsc561/hbase-master
    environment:
       - JAVA_HOME=/usr/lib/jvm/default-jvm
