pipeline:
  check_params:
    image: mongo:3.2.9
    commands:
        - cat lab3b/lab3b.js
        - sleep 15 
 
  grade_lab3b:
    image: mongo:3.2.9
    commands:
        - mongo --host mongodb < lab3b/lab3b.js 

services:
  mongodb:
    image: mongo:3.2.9
    command: [ --smallfiles ]
